import { Montserrat, Roboto,Roboto_Slab,Varela_Round,Sora} from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'

const montserrat = Montserrat({
  // variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700"], // ✅ bold added
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})

const roboto = Roboto({
  // variable: "--font-geist-sans",
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const robotoSlab = Roboto_Slab({
  // variable: "--font-geist-sans",
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-slab',
})

const varelaRound = Varela_Round({
  weight: "400",              // ✅ prop নাম weight (একবচন)
  subsets: ["latin"],
  display: "swap",
  variable: "--font-varela-round",
});

const sora = Sora({
  weight: "400",              // ✅ prop নাম weight (একবচন)
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sora",
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${roboto.variable} ${robotoSlab.variable} ${varelaRound.variable} ${sora.variable} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
